### ISSUE TITLE
Project Pitch Night Proposal

### ISSUE THREAD

**Issue by wdoug** [codefordenver/project-bootstrapper#14]

**Comment by Paul-McCarthy** [comment]
My notes from our discussion on 3/14:

What problem do we want to use software to solve?
Why is it important?
Should we work on it?
How?

What challenge do we want to work on?

**Comment by Paul-McCarthy** [comment]
Based on our discussion and input from everyone, I would propose the following agenda: 

*_Agenda: *_

1-minute:   Pitch the problem or challenge that you’d like to solve.  (2 to 10 minutes total for all pitches)

25-minute Pomodoro:     Break-out to get more info/Q&A from champion of each problem. Science-fair style in different corners of the room.

25-minute Pomodoro: Choose a problem that interests you and join that group to begin figuring out the scope and feasibility of making it a project for CFD. 

10-minute Stand-up:        Listen to the updates from each group.

5-minute voting:              Let everyone in attendance cast their vote for the top 1 or 2 projects.

5-minute results of voting:     Only necessary if we do some sort of private/semi-private voting

**Comment by wdoug** [comment]
I think we at least have the initial guidelines for this written up here: https://github.com/codefordenver/projects/blob/master/ISSUE_TEMPLATE.md

Should I close this issue @Paul-McCarthy?
