### ISSUE TITLE
New projects owned by user, NOT Code For Denver

### ISSUE THREAD

**Issue by Dsenza** [codefordenver/project-bootstrapper#15]
When a user creates a new Waffleboard and Repo using the bootstrapper, it's created under their username.

Should the bootstrapper create these under the CfD organization instead?

**Comment by wdoug** [comment]
Yeah. I'm not entirely sure. If there are a bunch created that don't pan out, we probably don't want them spamming and overflowing the Code for Denver org. For now it should be fairly straight forward to transfer them to the Code for Denver organization (I think). Actually, I'm not sure what happens to the waffle board when you do that.

**Comment by wdoug** [comment]
@whitebird08 what happened when you transferred your new repo to the Code for Denver organization?

**Comment by wdoug** [comment]
@Dsenza, yeah the transfer process kind of a pain, and definitely not the most intuitive at the moment, so I think it would be great to update it to (at least have the option) to be directly owned from Code for Denver initially.
