### ISSUE TITLE
Create 'Reach out to Partners' card

### ISSUE THREAD

**Issue by wdoug** [codefordenver/project-bootstrapper#17]

**Comment by abw1914** [comment]
See this link - [](https://docs.google.com/document/d/10Dy7pY5qMwSkvL_vf1_2RdUVEvt6Ti9yeNSeEAZKgxE/edit?usp=sharing)

**Comment by abw1914** [comment]
Willy,
See this link on the pitch idea process.  Let me know if this is what is needed.  Thanks

https://docs.google.com/document/d/10Dy7pY5qMwSkvL_vf1_2RdUVEvt6Ti9yeNSeEAZKgxE/edit?usp=sharing
